### ISSUE TITLE
Meta-Daten eines ausgewählten Titels ändern

### ISSUE THREAD

**Issue by Andreasm11** [Andreasm11/Musikbibliothek#3]
**Als Nutzer**
**möchte ich** die Meta-Daten eines ausgewählten Titels ändern
**damit ich** Fehler korrigieren oder Informationen nachtragen kann. (z.B. Titel, Künstler, Album und Erscheinungsjahr)

Akzeptanzkriterien:

- [x] Der Benutzer sollte in der Lage sein, über den CLI die Meta-Daten eines existierenden Titels zu änder
- [x] Nach der Änderung sollten die aktualisierten Meta-Daten des Songs in der Bibliothek angezeigt werden
- [x] Es sollte sichergestellt werden, dass der Titel existiert, bevor die Meta-Daten geändert werden können 
- [ ] Fehlerhafte Eingaben sollten abgefangen werden und eine erneute Eingabe sollte möglich sein (z.B. Worte bei Erscheinungsjahr)
- [x] CLI sollte durch den Prozess leiten 
- [x] mehrere Sachen sollten im selben Prozess bearbeitbar sein
- [x] Ausgabe nach erfolgreicher Änderung
