### ISSUE TITLE
Nach Titel oder Meta-Daten in der Bibliothek suchen

### ISSUE THREAD

**Issue by Andreasm11** [Andreasm11/Musikbibliothek#5]
**Als Nutzer**
**möchte ich** nach Titel oder Meta-Daten in der Bibliothek suchen
**damit ich** den gewünschten Song schnell und einfach finden kann

Akzeptanzkriterien:

- [x] Der Benutzer sollte in der Lage sein, über den CLI nach einem spezifischen Titel, Künstler, Album oder Erscheinungsjahr zu suchen
- [x] Die CLI sollte dann alle Songs anzeigen, welche den Suchbegriff enthalten
- [ ] Es sollte eine kombinierte Suche ermöglicht werden, indem man mehrere Suchkriterien gleichzeitig angibt
- [ ] wenn keine Übereinstimmung gefunden wird, sollte die CLI dem Benutzer mitteilen, dass keine Ergbenisse für die Suchkriterien vorliegen und fragen ob eine erneute Suche durchgeführt werden soll
